### ISSUE TITLE
nodes status showing as unknown

### ISSUE THREAD

**Issue by srivasthav89** [bloomberg/powerfulseal#114]
After running powerfulseal in autonomous mode status of the nodes are reported as status:Unknown which blocks us to delete the nodes in UI also performed the same in interactive mode but nodes are not being deleted, o/p. from cli shows "Deleted 1 nodes": but no node is deleted.

**Comment by seeker89** [comment]
What cloud driver are you using ? What version of the Seal ?

Could you paste the command you use to start the Seal (without any passwords/IDs obviously) ?


Thanks !

**Comment by srivasthav89** [comment]
1. seal autonomous --kubeconfig /Users/<id>/.kube/config --inventory-kubernetes --host localhost --port 8080 --policy-file policy.yaml --no-cloud
version: 2.0.1

2. [node no=104 id=fake-ip-10-223-9-47 ip=ip-10-223-9-47 az=nope groups=['amd64', 'c5.4xlarge', 'ip-10-223-9-47', 'linux', 'true', 'us-west-2', 'us-west-2c'] name=local-ip-10-223-9-47 state=NodeState.UNKNOWN]
Proceed ? (yes|no): "yes"
Deleting
2019-04-05 09:25:25 ELSML01SDKL powerfulseal.clouddrivers.no_cloud_driver[56770] ERROR Trying to delete things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
Deleted 1 nodes

**Comment by seeker89** [comment]
I can see that you are running the Seal with `--no-cloud` option - that means, that it won't be able to do anything to do with nodes. It says that in the error message.

If you want to take nodes up and down, you will need to use one of the provided drivers (aws, openstack, etc). What cloud are you using ?

**Comment by srivasthav89** [comment]
Got it, At present am using aws, so when i tag it with aws i see a different error.
```ruby
seal autonomous --kubeconfig /Users/sd9150/.kube/config --inventory-kubernetes --host localhost --port 8080 --policy-file policy.yaml --aws
2019-04-05 10:54:57  powerfulseal[64427] INFO Creating kubernetes client with config /Users/sd9150/.kube/config
2019-04-05 10:54:57  powerfulseal.k8s.k8s_client[64427] INFO Initializing with config: /Users/sd9150/.kube/config
2019-04-05 10:54:57  powerfulseal[64427] INFO Building AWS driver
2019-04-05 10:54:58  powerfulseal[64427] INFO Attempting to read the inventory from kubernetes
2019-04-05 10:54:58  powerfulseal.clouddrivers.aws_driver[64427] INFO Synchronizing remote nodes
2019-04-05 10:54:58  powerfulseal.clouddrivers.aws_driver[64427] INFO Synchronizing remote nodes
Traceback (most recent call last):
  File "/usr/local/bin/seal", line 11, in <module>
    sys.exit(start())
  File "/usr/local/lib/python2.7/site-packages/powerfulseal/cli/__main__.py", line 575, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/powerfulseal/cli/__main__.py", line 438, in main
    inventory.sync()
  File "/usr/local/lib/python2.7/site-packages/powerfulseal/node/node_inventory.py", line 98, in sync
    driver.sync()
  File "/usr/local/lib/python2.7/site-packages/powerfulseal/clouddrivers/aws_driver.py", line 59, in sync
    self.amount_of_servers = list(self.conn.instances.all())
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/Users/sd/Library/Python/2.7/lib/python/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/sd9150/Library/Python/2.7/lib/python/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/sd9150/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/sd9150/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the **DescribeInstances operation: You are not authorized to perform this operation.** 
```

**Comment by seeker89** [comment]
Hey !

Just double checking - are your AWS credentials all set correctly ? Check this link if you're unsure: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration

**Comment by srivasthav89** [comment]
Hi,
Checked the configurations now it has trouble reaching the nodes *Couldn't match IP to cloud node: ip-10-xxx-xx-xx*

**Comment by seeker89** [comment]
Hey @srivasthav89 

I'm guessing that you are trying to access the machines from outside AWS, in which case you probably want to use `'--use-private-ip'` flag that was implemented in https://github.com/bloomberg/powerfulseal/pull/107

**Comment by seeker89** [comment]
Closing due to inactivity.
