### ISSUE TITLE
Add the ability to use in-cluster config when running powerfulseal as a pod on kubernetes cluster

### ISSUE THREAD

**Issue by ksatchit** [bloomberg/powerfulseal#161]
**Is your feature request related to a problem? Please describe.**

- The recent introduction of powerfulseal [docker container](https://github.com/bloomberg/powerfulseal/blob/master/build/Dockerfile), has enabled deploying it as a kubernetes pod (typically controlled via a higher-level controller such as job/deploy/daemonset) in order to have a native/local service on the cluster itself to periodically inject chaos on the application pods and services. This also opens up the possibilities to allow the seal to be operated in a kubernetes-native way, via CRDs etc.,

- Using it in the  described manner  was seen to result in an error shown below - when attempting to list the pods under test, caused due to the non-availability of the cluster's kubeconfig file as argument to the powerfulseal binary. 

```
2019-09-26 03:26:44 powerfulseal-6674db84c6-znwjt powerfulseal[1] INFO modules powerfulseal.cli.__main__ : verbosity None : log level DEBUG : handler level ERROR 
2019-09-26 03:26:44 powerfulseal-6674db84c6-znwjt powerfulseal[1] INFO Creating kubernetes client with config /root/.kube/config
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 10, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 641, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 451, in main
    k8s_client = K8sClient(kube_config=kube_config)
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/k8s/k8s_client.py", line 29, in __init__
    kubernetes.config.load_kube_config(config_file=kube_config)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 653, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 621, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 503, in __getitem__
    v = self.safe_get(key)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 499, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable
```

**Describe the solution you'd like**

- It is desired to have the ability to access the kubernetes api-server from within the pod using the `InClusterConfig`. As per my understanding, this should help with making the seal more platform agnostic. 

  References: 
     - https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
     - https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py

**Describe alternatives you've considered**

- Workaround is to provide the kubeconfig as a configmap & mount it to the desired location on the pod (--no-cloud driver) . However, in case of clusters like GKE, we may need to perform additional steps (gcloud authentication etc.,) & pass on this information into the pod (gcloud config files) 

**Additional context**

- As part of the workaround, burned in the gcloud environment with service account key json file & kubeconfig into the powerfulseal container & attempted to run the chaos - however, it fails with the following error: 

```
root@powerfulseal-76c97859d9-46ckp:/# powerfulseal autonomous --inventory-kubernetes --no-cloud --policy-file=/root/policy_kill_random_default.yml
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal[8] INFO modules powerfulseal.cli.__main__ : verbosity None : log level DEBUG : handler level ERROR 
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal[8] INFO Creating kubernetes client with config /root/.kube/config
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal.k8s.k8s_client[8] INFO Initializing with config: /root/.kube/config
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal[8] INFO No driver - some functionality disabled
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal[8] INFO Attempting to read the inventory from kubernetes
2019-09-26 05:40:08 powerfulseal-76c97859d9-46ckp powerfulseal.k8s.k8s_client[8] ERROR (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1aa686d3-b465-4bd9-82c6-88cf8b712a9d', 'Content-Type': 'application/json', 'Date': 'Thu, 26 Sep 2019 05:40:08 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/k8s/k8s_client.py", line 80, in list_nodes
    resp = self.client_corev1api.list_node()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 13726, in list_node
    (data) = self.list_node_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 13821, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 166, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 356, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1aa686d3-b465-4bd9-82c6-88cf8b712a9d', 'Content-Type': 'application/json', 'Date': 'Thu, 26 Sep 2019 05:40:08 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```
- However, the kubectl commands (also installed the kubectl binary inside the container as part of the debug) do show the api-server is reachable: 

```
root@powerfulseal-76c97859d9-46ckp:/# kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
hello-deploy-6df5559bbd-ngsjw   1/1     Running   0          15h
hello-deploy-6df5559bbd-vz2wj   1/1     Running   0          15h
powerfulseal-76c97859d9-46ckp   1/1     Running   0          9m3s
```
- See the same issue when I changed the cloud-provider to `gcp` (pointed the --gcp-config-file to the key, but I suppose this is incorrect)

**Comment by seeker89** [comment]
Very good point, thanks so much for reporting this. It looks like an easy fix - if the config is provided, use it, if not, default to in cluster one.
