### ISSUE TITLE
with powerfulseal2.7.0,  creating kubernetes client fails.

### ISSUE THREAD

**Issue by datatonic** [bloomberg/powerfulseal#177]
**Describe the bug**
with powerfulseal2.7.0,  creating kubernetes client fails.
Kubernetes version 

kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:11:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
 

**To Reproduce**

This is   a k8s cluster  deployed  on an Openstack environment with three master  k8s nodes. I am running powerfulseal in a container.  The container is built from github Dockerfile.
I am running it as 

_sudo docker exec -it   powerfulseal_from_github_c  powerfulseal   interactive  --kubeconfig /etc/kubernetes/admin.conf  --inventory-kubernetes   --openstack_

2019-10-18 19:08:53 b85dc4e6b3bb powerfulseal.cli.__main__[61] INFO Creating kubernetes client with config /etc/kubernetes/admin.conf from --kubeconfig flag
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 680, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 484, in main
    k8s_client = K8sClient(kube_config=kube_config)
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/k8s/k8s_client.py", line 29, in __init__
    kubernetes.config.load_kube_config(config_file=kube_config)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 653, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 621, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 503, in __getitem__
    v = self.safe_get(key)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 499, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable

**Expected behavior**
I should see  it find out all  the k8s nodes. 

**Screenshots**

**Environment (please complete the following information):**
 - Centos Linux kubernetes-master-rtp-aio-25-1 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by seeker89** [comment]
You're passing `--kubeconfig /etc/kubernetes/admin.conf` as the config, but you're not actually asking docker to insert any files from your host filesystem into your container.

Did you prebake the file into your image ? Is the powerfulseal container deployed via k8s or via docker run ?

If you just want to exec into a container running on k8s, like in the examples from readme, then skip the `--kubeconfig` flag altogether - the seal will try to use the in-cluster configuration injected by kubernetes.

**Comment by seeker89** [comment]
Will close for now, please feel free to reopen if you are still seeing issues.
