### ISSUE TITLE
UI and prometheus metrics don't work in autonomous mode

### ISSUE THREAD

**Issue by monolithh** [bloomberg/powerfulseal#179]
**Describe the bug**
When I try to run `powerfulseal` in autonomous mode with enabled UI and Prometheus metrics UI goes broken

**To Reproduce**
I have faced with this issue on the official docker image `2.7.0`
I run the image with the following arguments:
```-vv
      - autonomous
      - --inventory-kubernetes
      - --aws
      - --policy-file=/root/policy.yaml
      - --use-pod-delete-instead-of-ssh-kill
      - --host=0.0.0.0
      - --port=8080
      - --prometheus-collector
      - --prometheus-host=0.0.0.0
      - --prometheus-port=9000
```
The whole log:
```
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal[1] INFO modules powerfulseal.cli.__main__ : verbosity 2 : log level DEBUG : handler level INFO
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal.cli.__main__[1] INFO Creating kubernetes client with in-cluster config
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal.k8s.k8s_client[1] INFO Initializing with config: None
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal[1] INFO Building AWS driver
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal[1] INFO Attempting to read the inventory from kubernetes
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal.node.node_inventory[1] INFO Sync Nodes
2019-10-30 13:54:19 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[1] INFO Synchronizing remote nodes
2019-10-30 13:54:20 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[1] INFO Fetched X remote servers
2019-10-30 13:54:23 powerfulseal-56c77748d8-np6fx powerfulseal[1] INFO Starting prometheus metrics server on 9000
2019-10-30 13:54:23 powerfulseal-56c77748d8-np6fx powerfulseal.web.server[1] INFO Starting policy runner
2019-10-30 13:54:23 powerfulseal-56c77748d8-np6fx powerfulseal[1] INFO Starting the UI server
 * Serving Flask app "powerfulseal.web.server" (lazy loading)
 * Environment: development
 * Debug mode: on
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Matched X pods in namespace XXXXX
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Initial set length: X
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Filtered set length: X
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Deleting pod [ ... ]
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal[12] INFO modules powerfulseal.cli.__main__ : verbosity 2 : log level DEBUG : handler level INFO
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.cli.__main__[12] INFO Creating kubernetes client with in-cluster config
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal.k8s.k8s_client[12] INFO Initializing with config: None
2019-10-30 13:54:24 powerfulseal-56c77748d8-np6fx powerfulseal[12] INFO Building AWS driver
2019-10-30 13:54:25 powerfulseal-56c77748d8-np6fx powerfulseal[12] INFO Attempting to read the inventory from kubernetes
2019-10-30 13:54:25 powerfulseal-56c77748d8-np6fx powerfulseal.node.node_inventory[12] INFO Sync Nodes
2019-10-30 13:54:25 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[12] INFO Synchronizing remote nodes
2019-10-30 13:54:25 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[12] INFO Fetched X remote servers
2019-10-30 13:54:28 powerfulseal-56c77748d8-np6fx powerfulseal[12] INFO Starting prometheus metrics server on 9000
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 10, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 680, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 582, in main
    start_http_server(args.prometheus_port, args.prometheus_host)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 130, in start_http_server
    httpd = _ThreadingSimpleServer((addr, port), CustomMetricsHandler)
  File "/usr/local/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2019-10-30 13:57:53 powerfulseal-56c77748d8-np6fx powerfulseal.node.node_inventory[1] INFO Sync Nodes
2019-10-30 13:57:53 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[1] INFO Synchronizing remote nodes
2019-10-30 13:57:53 powerfulseal-56c77748d8-np6fx powerfulseal.clouddrivers.aws_driver[1] INFO Fetched X remote servers
2019-10-30 13:57:56 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Matched X pods in namespace XXXX
2019-10-30 13:57:56 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Initial set length: X
2019-10-30 13:57:56 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Filtered set length: X
2019-10-30 13:57:56 powerfulseal-56c77748d8-np6fx powerfulseal.policy.scenario.Kill a pod[1] INFO Deleting pod [ ... ]
```
Check sockets in LISTEN state after I saw python traceback:
```
ss -tnlp
State                       Recv-Q                      Send-Q                                            Local Address:Port                                             Peer Address:Port
LISTEN                      0                           5                                                       0.0.0.0:9000                                                  0.0.0.0:*                          users:(("powerfulseal",pid=1,fd=6))
```

As I can see for some reasons after first loop (when it kills a pod) powerfulseal with PID 1 spawns his own fork (child) with PID 12. PID 12 tries to open socket for Prometheus metrics but the port had already opened by PID 1. After all of this UI goes broken (powerfulseal just closes port) but Prometheus metrics available. 
However, I see python traceback and UI goes broken but powerfulseal continue working and killing pods/nodes

**Expected behavior**
Both UI and Prometheus metrics in working state

**Environment (please complete the following information):**
- docker image: `powerfulseal:2.7.0`
- cloud provider: `AWS`

**Additional context**
Even though prometheus metrics work in this case they look weird and uninformative:
```
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 438788096.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 113250304.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1572443658.21
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 7.24
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 65536.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="4",version="3.7.4"} 1.0
# HELP seal_pod_kills_total Number of pods killed (including failures)
# TYPE seal_pod_kills_total counter
# HELP seal_nodes_stopped_total Number of nodes stopped (including failures)
# TYPE seal_nodes_stopped_total counter
# HELP seal_execute_failed_total Increasing counter for command execution failures
# TYPE seal_execute_failed_total counter
# HELP seal_empty_filter_total Increasing counter for cases where filtering returns an empty result
# TYPE seal_empty_filter_total counter
seal_empty_filter_total 0.0
# HELP seal_probability_filter_not_passed_total Increasing counter for cases where the probability filter does not pass any nodes
# TYPE seal_probability_filter_not_passed_total counter
seal_probability_filter_not_passed_total 0.0
# HELP seal_empty_match_total Increasing counter for cases where matching returns an empty result
# TYPE seal_empty_match_total counter
seal_empty_match_total{source="nodes"} 0.0
seal_empty_match_total{source="pods"} 0.0
```

At that moment when I copy metrics `powerfulseal` has already killed some pods. Why I don't see this information in metrics?

**Comment by seeker89** [comment]
Thanks for raising this. Will look into this soon.

**Comment by seeker89** [comment]
Hi there, sorry for taking a while to get to this. Excellent write up, by the way, very helpful.

I can confirm, that the metrics don't seem to be updating, just like you described, but I'm not seeing the error you describe when running the seal locally. Would it be possible to test the same policy file you've written with an outside instance to see whether the problem is connected to the way we build the docker image?

Thanks! 👍

**Comment by monolithh** [comment]
@seeker89 Seems this issue somehow related to the powerfulseal docker image/container. When I ran this locally I didn't face the issue.

One moment we should take into account: the main process spawns child. This is not a separate process which is trying to open already-opened port - this is powerfulseal's child.
 ```
          ...               /bin/bash  
 3224 pts/0    Sl+    0:01  \_ /usr/local/bin/python /usr/local/bin/powerfulseal -vv autonomous --inventory-kubernetes .....
 3325 pts/0    R+     0:01      \_ /usr/local/bin/python /usr/local/bin/powerfulseal -vv autonomous --inventory-kubernetes ....
```

**Comment by monolithh** [comment]
@seeker89 Can you reproduce the issue with the docker image as described in this Issue?

**Comment by seeker89** [comment]
The only thing I can think of which would start a child process would be the debug mode.
I notice this in your logs:

```
 * Serving Flask app "powerfulseal.web.server" (lazy loading)
 * Environment: development
 * Debug mode: on
[ ... ]
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
```

I've run it from the same container, and it works fine, but it defaults to production mode. Did you add any `FLASK_ENV` or `FLASK_DEBUG` variables to your container?

**Comment by monolithh** [comment]
@seeker89 Yes, I did
```
      - name: FLASK_ENV
        value: development
      - name: FLASK_DEBUG
        value: "1"
```
Going to test without these variables

**Comment by seeker89** [comment]
Yeah, so `prometheus_exporter` `start_http_server` doesn't seem to be compatible with Flask.

From https://pypi.org/project/prometheus-flask-exporter/ :

> Please note, that changes being live-reloaded, when running the Flask app with debug=True, are not going to be reflected in the metrics. See https://github.com/rycus86/prometheus_flask_exporter/issues/4 for more details.

> Alternatively - since version 0.5.1 - if you set the DEBUG_METRICS environment variable, you will get metrics for the latest reloaded code. These will be exported on the main Flask app. Serving the metrics on a different port is not going to work most probably - e.g. PrometheusMetrics.start_http_server(..) is not expected to work.

So I think the easiest way around it would be to either run the prometheus metrics on the same flask application, or try to prevent calling `start_http_server` on reloads.

**Comment by monolithh** [comment]
@seeker89 Yes, you are totally right. I have removed `FLASK_ENV` and `FLASK_DEBUG` and the issue has gone. 

But what about prometheus metrics? Could you please take a look why they are uninformative? 
This information would be very helpful:
```
# HELP seal_pod_kills_total Number of pods killed (including failures)
# TYPE seal_pod_kills_total counter
# HELP seal_nodes_stopped_total Number of nodes stopped (including failures)
# TYPE seal_nodes_stopped_total counter
```

**Comment by seeker89** [comment]
The metrics for pods killed got damaged: please take this for a spin https://github.com/bloomberg/powerfulseal/pull/190 ?

The node stopped metric seems to be intact - I don't see in your logs any node scenarios stopping the machines?

**Comment by monolithh** [comment]
@seeker89 Yes I can confirm that with nodes metrics everything is fine
```
# TYPE seal_nodes_stopped_total counter
seal_nodes_stopped_total{id="i-XXXXXXXXXX",name="",status="success"} 1.0
```

When will the new docker image with the fixes above be available? 

Thank you a lot. It seems to me this issue can be closed

**Comment by seeker89** [comment]
Hopefully tomorrow before EOD.
