### ISSUE TITLE
Seal crashed trying to kill a pod with ContainerCreating status.

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#197]
**Describe the bug**
Unhandled exception while trying to kill a pod that has ```ContainerCreating``` status.

This issue is a regression from #127 

**To Reproduce**
```
(seal) $ pods sock-shop
[pod #0 name=carts-6bfcf84f4-lqqss namespace=sock-shop containers=1 ip=10.8.1.4 host_ip=10.128.0.28 state=Running labels:name=carts,pod-template-hash=6bfcf84f4]
[pod #1 name=carts-db-6bfc588c5f-vdpmc namespace=sock-shop containers=1 ip=10.8.1.3 host_ip=10.128.0.28 state=Running labels:name=carts-db,pod-template-hash=6bfc588c5f]
[pod #2 name=catalogue-77d4f66dbf-x28j9 namespace=sock-shop containers=1 ip=None host_ip=10.128.0.28 state=ContainerCreating labels:name=catalogue,pod-template-hash=77d4f66dbf]
[pod #3 name=catalogue-db-99cbcbb88-j4nqs namespace=sock-shop containers=1 ip=None host_ip=10.128.0.28 state=ContainerCreating labels:name=catalogue-db,pod-template-hash=99cbcbb88]
[pod #4 name=front-end-b5f568888-8nrk8 namespace=sock-shop containers=1 ip=10.8.0.6 host_ip=10.128.0.11 state=Running labels:name=front-end,pod-template-hash=b5f568888]
[pod #5 name=orders-54d7666f75-8287r namespace=sock-shop containers=1 ip=None host_ip=10.128.0.28 state=ContainerCreating labels:name=orders,pod-template-hash=54d7666f75]
[pod #6 name=orders-db-7888765df9-5szbz namespace=sock-shop containers=1 ip=10.8.0.7 host_ip=10.128.0.11 state=Running labels:name=orders-db,pod-template-hash=7888765df9]
[pod #7 name=payment-7d8497bcd7-q4wn7 namespace=sock-shop containers=1 ip=10.8.0.8 host_ip=10.128.0.11 state=Running labels:name=payment,pod-template-hash=7d8497bcd7]
[pod #8 name=queue-master-6bb75d8867-56jqd namespace=sock-shop containers=1 ip=10.8.0.9 host_ip=10.128.0.11 state=Running labels:name=queue-master,pod-template-hash=6bb75d8867]
[pod #9 name=rabbitmq-5786759fc9-d8pmx namespace=sock-shop containers=1 ip=10.8.2.6 host_ip=10.128.0.25 state=Running labels:name=rabbitmq,pod-template-hash=5786759fc9]
[pod #10 name=shipping-58bc954d85-m277d namespace=sock-shop containers=1 ip=10.8.0.10 host_ip=10.128.0.11 state=Running labels:name=shipping,pod-template-hash=58bc954d85]
[pod #11 name=user-6b5f6896c4-rclcv namespace=sock-shop containers=1 ip=10.8.2.7 host_ip=10.128.0.25 state=Running labels:name=user,pod-template-hash=6b5f6896c4]
[pod #12 name=user-db-6d5c9f6d84-44l65 namespace=sock-shop containers=1 ip=None host_ip=10.128.0.28 state=ContainerCreating labels:name=user-db,pod-template-hash=6d5c9f6d84]
```
```
(seal) $ kill 2
Traceback (most recent call last):
  File "/home/danielgonzalezlopes/.local/bin/powerfulseal", line 10, in <module>
    sys.exit(start())
  File "/home/danielgonzalezlopes/.local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 684, in start
    main(sys.argv[1:])
  File "/home/danielgonzalezlopes/.local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 562, in main
    cmd.cmdloop()
  File "/usr/local/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/danielgonzalezlopes/.local/lib/python3.7/site-packages/powerfulseal/cli/pscmd.py", line 460, in do_kill
    cmd = self.executor.get_kill_command(container_id.replace("docker://",""))
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Why this happens?**
It looks like https://github.com/bloomberg/powerfulseal/commit/47f1c139957d229cf7a7b158755d2f525b4df6a7 changed state from `state.phase`  to `state.reason`. But when we try to kill a pod we still check if it's on `Pending` state.phase:
https://github.com/bloomberg/powerfulseal/blob/364d7f7705d95f95d6fb69677e12d0ab425d8039/powerfulseal/cli/pscmd.py#L439

**Expected behavior**
Tell me I can't kill it :)

**Comment by dgzlopes** [comment]
Also, we don't highlight the new "states"! Maybe adding them to the [list](https://github.com/bloomberg/powerfulseal/blob/364d7f7705d95f95d6fb69677e12d0ab425d8039/powerfulseal/cli/pscmd.py#L36) is useful.

@seeker89 Maybe this issue could be labeled as a `good first issue`.

**Comment by seeker89** [comment]
Good call, labeled `good first issue`!
