### ISSUE TITLE
NodeScenario failed

### ISSUE THREAD

**Issue by white-cloud** [bloomberg/powerfulseal#198]
Hello, 
 I'm trying to execute the nodeScenario, but it doesn't work for me i don't know why, i even replaced the name by the ip but still not working for me .

apiVersion: v1
kind: ConfigMap
metadata:
name: policy
namespace: default
data:
policy_kill_random_default.yml: |-
config:
loopsNumber: 1
nodeScenarios:
- name: "delete one node"
match:
- property:
name: "name"
selector: "the name of mynode"
filters:
- dayTime:
onlyDays:
- "wednesday"
startTime:
hour: 16
minute: 02
second: 0
endTime:
hour: 19
minute: 30
second: 0
actions:
- stop:
force: true
I wanna make sure please if my setup up is right? 

Thank you.

**Comment by white-cloud** [comment]
Hello @seeker89 , 

Please any help with this issue, because i need a way to execute my node failure scenario .

Thank you.

**Comment by dgzlopes** [comment]
Hi @white-cloud, sorry for the late response.

If you run Powerfulseal inside K8s using the example provided in [./kubernetes](https://github.com/bloomberg/powerfulseal/tree/master/kubernetes), you can't run node scenarios. They require direct interaction with a specific cloud provider using your host's configuration.

From reading the Deployment [manifest](https://github.com/bloomberg/powerfulseal/blob/master/kubernetes/powerfulseal.yml#L28,L57) I see that Powerfulseal is started with the `--no-cloud` flag.  Even if you change this flag, the container would need to ship with the set of [credentials/requirements](https://github.com/bloomberg/powerfulseal#cloud-provider-requirements) required by your cloud provider.


In any case, you can run Powerfulseal [outside](https://github.com/bloomberg/powerfulseal#running-outside-of-the-cluster) the cluster.  It is really straightforward and could be a good starting point for testing your scenarios.

**Comment by amarAkula** [comment]
Can we delete a node from the cluster ?
I tried this by specifying the node scenario in the policy file, but it is not being deleted or stopped.
Here is the policy file.
config:
  loopsNumber: 1
  minSecondsBetweenRuns: 1
  maxSecondsBetweenRuns: 30

nodeScenarios: 

  - name: "kill all the baddies"

    match:
      - property:
          name: "name"
          value: "local-onpremvm05.*"
          
    filters:
      - property:
          name: "name"
          value: "local-onpremvm05.*"
      - property:
          name: "ip"
          value: "onpremvm05.konylabs.net"

    actions:
      - stop:
          force: false
      - wait:
          seconds: 30
      - start:
podScenarios:
  - name: "delete random pods in kubernetes-dashboard namespace"

    match:
      - namespace:
          name: "kubernetes-dashboard"

    filters:
      - randomSample:
          size: 1

    actions:
      - kill:
          probability: 0.77
          force: true

===========================LOGS==================================
[root@onpremvm13 ~]# seal autonomous --kubeconfig /root/.kube/config --no-cloud --inventory-kubernetes --ssh-allow-missing-host-keys --policy-file /root/chaos/examCofig.yaml --stdout-collector
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal[47645] INFO modules powerfulseal.cli.__main__ : verbosity None : log level DEBUG : handler level ERROR
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.cli.__main__[47645] INFO Creating kubernetes client with config /root/.kube/config from --kubeconfig flag
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.k8s.k8s_client[47645] INFO Initializing with config: /root/.kube/config
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal[47645] INFO No driver - some functionality disabled
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal[47645] INFO Attempting to read the inventory from kubernetes
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.node.node_inventory[47645] INFO Sync Nodes
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] INFO Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal[47645] INFO Using stdout metrics collector
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.web.server[47645] INFO Starting policy runner
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Initial set length: 6
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Filtered set length: 1
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Acting on these: [[node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]]
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action stop on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Node stopped - uid: fake-onpremvm05.konylabs.net - name: local-onpremvm05.konylabs.net
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] ERROR Trying to stop things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal[47645] INFO Starting the UI server
 * Serving Flask app "powerfulseal.web.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/bin/seal", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.6/site-packages/powerfulseal/cli/__main__.py", line 684, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/powerfulseal/cli/__main__.py", line 626, in main
    start_server(args.host, args.port, args.accept_proxy_headers)
  File "/usr/local/lib/python3.6/site-packages/powerfulseal/web/server.py", line 257, in start_server
    app.run(host=host, port=port)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action start on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] ERROR Trying to start things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action execute 'echo spread some chaos' on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'echo spread some chaos']' on local-onpremvm05.konylabs.net
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'echo spread some chaos']' on local-onpremvm05.konylabs.net failed with error: Error creating SSH connection
Original error: No authentication methods available
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Error return code: {'ret_code': 1, 'error': 'Error creating SSH connection\nOriginal error: No authentication methods available'}
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Execute failed - uid: fake-onpremvm05.konylabs.net - name: local-onpremvm05.konylabs.net
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Matched 2 pods in namespace kubernetes-dashboard
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Initial set length: 2
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Filtered set length: 1
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Action execute 'sudo docker kill -s SIGKILL 764612fbea8b4c5dd335775cae91ede731c49801c84d51da3405e14a2d9c20de' on [pod #0 name=dashboard-metrics-scraper-6c554969c6-w47pk namespace=kubernetes-dashboard containers=1 ip=10.32.0.35 host_ip=10.10.24.205 state=Running labels:k8s-app=dashboard-metrics-scraper,pod-template-hash=6c554969c6]
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 764612fbea8b4c5dd335775cae91ede731c49801c84d51da3405e14a2d9c20de']' on local-10.10.24.205
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 764612fbea8b4c5dd335775cae91ede731c49801c84d51da3405e14a2d9c20de']' on local-10.10.24.205 failed with error: Error creating SSH connection
Original error: No authentication methods available
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Error return code: {'ret_code': 1, 'error': 'Error creating SSH connection\nOriginal error: No authentication methods available'}
2020-03-02 16:20:07 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Pod killed - namespace: kubernetes-dashboard - name: dashboard-metrics-scraper-6c554969c6-w47pk
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.node.node_inventory[47645] INFO Sync Nodes
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] INFO Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Initial set length: 6
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Filtered set length: 1
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Acting on these: [[node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]]
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action stop on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Node stopped - uid: fake-onpremvm05.konylabs.net - name: local-onpremvm05.konylabs.net
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] ERROR Trying to stop things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action start on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.clouddrivers.no_cloud_driver[47645] ERROR Trying to start things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Action execute 'echo spread some chaos' on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'echo spread some chaos']' on local-onpremvm05.konylabs.net
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'echo spread some chaos']' on local-onpremvm05.konylabs.net failed with error: Error creating SSH connection
Original error: No authentication methods available
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.kill all the baddies[47645] INFO Error return code: {'ret_code': 1, 'error': 'Error creating SSH connection\nOriginal error: No authentication methods available'}
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Execute failed - uid: fake-onpremvm05.konylabs.net - name: local-onpremvm05.konylabs.net
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Matched 2 pods in namespace kubernetes-dashboard
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Initial set length: 2
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Filtered set length: 1
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Action execute 'sudo docker kill -s SIGKILL bc83a2997a8b0917d658a1e23ee577bb65fb2fadcc7befee6178de9671b97b6a' on [pod #1 name=kubernetes-dashboard-c46b85bbd-vdhs5 namespace=kubernetes-dashboard containers=1 ip=10.43.0.1 host_ip=10.10.24.144 state=Running labels:k8s-app=kubernetes-dashboard,pod-template-hash=c46b85bbd]
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL bc83a2997a8b0917d658a1e23ee577bb65fb2fadcc7befee6178de9671b97b6a']' on local-10.10.24.144
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.execute.remote_executor[47645] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL bc83a2997a8b0917d658a1e23ee577bb65fb2fadcc7befee6178de9671b97b6a']' on local-10.10.24.144 failed with error: Error creating SSH connection
Original error: No authentication methods available
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.policy.scenario.delete random pods in kubernetes-dashboard namespace[47645] INFO Error return code: {'ret_code': 1, 'error': 'Error creating SSH connection\nOriginal error: No authentication methods available'}
2020-03-02 16:20:12 onpremvm13.konylabs.net powerfulseal.metriccollectors.stdout_collector[47645] INFO Pod killed - namespace: kubernetes-dashboard - name: kubernetes-dashboard-c46b85bbd-vdhs5

**Comment by dgzlopes** [comment]
Hi @amarAkula

No. You can't run Node scenarios if you are running Powerfulseal inside the cluster. You have to run it [outside](https://github.com/bloomberg/powerfulseal#running-outside-of-the-cluster) and [configure](https://github.com/bloomberg/powerfulseal#cloud-provider-requirements) your cloud provider.

From your output log, you can see the error happening here:
```
...
INFO Action start on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]
...
ERROR Trying to start things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
...
```
Maybe a more specific error message for this case could be useful.

**Comment by amarAkula** [comment]
Hi @dgzlopes  
Since it is an on-premise installation, I'm not using any cloud driver.
Also it says node is being stopped through the logs, but  not actually.
From the above logs..
INFO Action stop on [node no=17 id=fake-onpremvm05.konylabs.net ip=onpremvm05.konylabs.net extIp=onpremvm05.konylabs.net az=nope groups=['amd64', 'linux', 'onpremvm05.konylabs.net'] name=local-onpremvm05.konylabs.net state=NodeState.UNKNOWN]

**Comment by dgzlopes** [comment]
Oh, ok! But yeah, right now Node scenarios require a cloud provider configuration. Powerfulseal uses the cloud provider Python client while trying to kill the node.

I think on that INFO message, Powerfulseal is saying... Hey! I'm running this scenario and I'm going to apply a STOP action. But it never happens. Also, you can see how the node state is marked as  UNKNOWN.

**Comment by amarAkula** [comment]
Thanks @dgzlopes for reaching out.

**Comment by seeker89** [comment]
Indeed, right now the node actions are done through the cloud provider.

If you're running with `--no-cloud` they get ignored. One way to improve that would be to just run `sudo reboot` on the node as an approximation of shutting it down.

**Comment by amarAkula** [comment]
You mean manually shut down and drain the nodes

**Comment by seeker89** [comment]
Yeah, we could tweak the seal to manually reboot the node, if you're not using a cloud provider. But probably not drain the node - simulate a machine crashing basically.

**Comment by amarAkula** [comment]
How can we do that ? can we reboot the node using seal

**Comment by seeker89** [comment]
Right now the no-cloud driver is a noop when it comes to stopping machines:

https://github.com/bloomberg/powerfulseal/blob/9030721cb0f14d802cf1afa3817837c9367516a6/powerfulseal/clouddrivers/no_cloud_driver.py#L55-L60

If during the initialising, we passed the ssh remote executor to it, we could instead make it execute `sudo reboot`

https://github.com/bloomberg/powerfulseal/blob/9030721cb0f14d802cf1afa3817837c9367516a6/powerfulseal/execute/remote_executor.py#L46

**Comment by amarAkula** [comment]
It does the same as manual reboot right?
With Cloud configuration, does powerfulseal schedhule deploy the pods of the killed node onto another node in the cluster?

**Comment by jcstanaway** [comment]
> If you run Powerfulseal inside K8s using the example provided in ./kubernetes, you can't run node scenarios. They require direct interaction with a specific cloud provider using your host's configuration.

We have a number of different clusters in different cloud providers in different regions. We're considering running an instance of seal per cluster within a single admin-type cluster.  Based on the above discussion, it appears we should be able to do this as long as we specify the cloud provider & cloud creds & SSH creds for each instance.  And it appears that we should also be able to run node scenarios as well since seal is running outside of the cluster that it is operating on.  Is that correct?

**Comment by dgzlopes** [comment]
Yes @jcstanaway, that's correct.
