### ISSUE TITLE
Exception raised when no pods match policy

### ISSUE THREAD

**Issue by jcstanaway** [bloomberg/powerfulseal#204]
**Describe the bug**
Just getting starting with seal and have a policy defined which intentionally does not match any pods.  Seal doesn't appear to handle this scenario as an exception is raised:

```
2020-03-27 21:31:04 powerfulseal-7f56dbffff-cvwvp powerfulseal.policy.scenario.delete random pods in default namespace[1] INFO Matched 0 pods for selector app=hello in namespace default
2020-03-27 21:31:04 powerfulseal-7f56dbffff-cvwvp powerfulseal.metriccollectors.stdout_collector[1] INFO Matched to empty set - source: pods
2020-03-27 21:31:04 powerfulseal-7f56dbffff-cvwvp powerfulseal.policy.scenario.delete random pods in default namespace[1] INFO Initial set length: 0
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 684, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 637, in main
    metric_collector=metric_collector
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/policy/policy_runner.py", line 91, in run
    scenario.execute()
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/policy/scenario.py", line 62, in execute
    filtered_set = self.filter(initial_set)
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/policy/scenario.py", line 103, in filter
    return self.filter_mapping(items, filters, mapping)
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/policy/scenario.py", line 187, in filter_mapping
    items = filter_method(items, filter_params)
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/policy/scenario.py", line 164, in filter_random_sample
    return random.sample(candidates, size)
  File "/usr/local/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

**To Reproduce**
1. Defined the following `policy.yml`:
```
config:
  minSecondsBetweenRuns: 1
  maxSecondsBetweenRuns: 10
nodeScenarios: []
podScenarios:
  - name: "delete random pods in default namespace"
    match:
      - labels:
          namespace: "default"
          selector: "app=hello"
    filters:
      - randomSample:
          size: 1
    actions:
      - kill:
          probability: 0.77
          force: true
```
2. Run seal: `powerfulseal autonomous --inventory-kubernetes --aws --policy-file=/usr/local/etc/powerfulseal/policy.yml --use-pod-delete-instead-of-ssh-kill --headless`
3. See error

**Expected behavior**
No errors.

**Screenshots**
n/a

**Environment (please complete the following information):**
Using image `store/bloomberg/powerfulseal:2.8.0`

**Additional context**
n/a

**Possible fix**
Appears that a simple check on the number of items in `initial_set` after line 61 in `scenario.py` would be sufficient.  If len(initial_set) == 0 then done.  I can submit a PR if desired.

**Comment by dgzlopes** [comment]
Good catch! I'm able to replicate it locally. 

Sure, if you have some time a PR is welcome. On the other hand,  maybe we should use `if not` to check if the `initial_set` is empty.

**Comment by jcstanaway** [comment]
This is what I was going to suggest:
```
        if len(initial_set) > 0:
            filtered_set = self.filter(initial_set)
            self.logger.debug("Filtered set: %r", filtered_set)
            self.logger.info("Filtered set length: %d", len(filtered_set))
            if len(filtered_set) > 0:
                self.act(filtered_set)
```

**Comment by dgzlopes** [comment]
That should work perfectly! But I was thinking about using the fact that empty sequences in [Python](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) are `False`:

```python
        initial_set = self.match()
        self.logger.debug("Initial set: %r", initial_set)
        self.logger.info("Initial set length: %d", len(initial_set))
        if initial_set:
            filtered_set = self.filter(initial_set)
            self.logger.debug("Filtered set: %r", filtered_set)
            self.logger.info("Filtered set length: %d", len(filtered_set))
            if filtered_set:
                self.act(filtered_set)
        self.logger.debug("Done")
```

It's just a small nit :)

**Comment by jcstanaway** [comment]
Sounds good - haven't used Python much.
