### ISSUE TITLE
Errors using validate and malformed policy

### ISSUE THREAD

**Issue by jcstanaway** [bloomberg/powerfulseal#209]
**Describe the bug**
When seal is called with `validate` command and invalid policy file, two issues arise:
1. Seal calls `os.exit()`.  `os.exit()` does not exist and results in python logging an error and stack trace.  Should instead be calling `sys.exit()`.  `os.exit()` is also called in one other place.
2. Seal outputs `Policy not valid. See log output above.` However, since the default log level had not yet been set up, there is no "output above".  If `is_policy_valid()`calls `logger.error()` (which is more appropriate in this case) instead of `logger.info()`, then the error details are provided.  Also suggest that `main()` calls `logger.error()` when `is_policy_valid()` fails in autonomous mode.

**To Reproduce**
1. Create malformed policy.yml file (in this case, deleted "match" object).
2. Execute `seal validate --policy-file=policy.yml`
3. See error
```
$ seal validate --policy-file=policy.yml
Policy not valid. See log output above.
Traceback (most recent call last):
  File "/Users/stanaway/.pyenv/versions/3.8.1/bin/seal", line 8, in <module>
    sys.exit(start())
  File "/Users/stanaway/.pyenv/versions/3.8.1/lib/python3.8/site-packages/powerfulseal/cli/__main__.py", line 684, in start
    main(sys.argv[1:])
  File "/Users/stanaway/.pyenv/versions/3.8.1/lib/python3.8/site-packages/powerfulseal/cli/__main__.py", line 448, in main
    return os.exit(1)
AttributeError: module 'os' has no attribute 'exit'
```

**Expected behavior**
No python errors & detailed error information about malformed policy file.
```
$ seal validate --policy-file=policy.yml
'match' is a required property

Failed validating 'required' in schema['properties']['podScenarios']['items']:
    {'additionalProperties': False,
     'properties': {'actions': {'items': {'oneOf': [{'$ref': '#/definitions/actionKillPod'},
                                                    {'$ref': '#/definitions/actionWait'}],
                                          'type': 'object'},
                                'type': 'array'},
                    'description': {'type': 'string'},
                    'filters': {'items': {'oneOf': [{'$ref': '#/definitions/filterPropertyPod'},
                                                    {'$ref': '#/definitions/filterDayTime'},
                                                    {'$ref': '#/definitions/filterRandomSample'},
                                                    {'$ref': '#/definitions/filterProbability'}],
                                          'type': 'object'},
                                'type': 'array'},
                    'match': {'items': {'oneOf': [{'$ref': '#/definitions/matchPodNamespace'},
                                                  {'$ref': '#/definitions/matchPodDeploymentAndNamespace'},
                                                  {'$ref': '#/definitions/matchPodLabelsAndNamespace'}]},
                              'type': 'array'},
                    'name': {'type': 'string'}},
     'required': ['name', 'match', 'filters', 'actions'],
     'type': 'object'}

On instance['podScenarios'][0]:
    {'actions': [{'kill': {'probability': 0.01}}],
     'filters': [{'property': {'name': 'state', 'value': 'Running'}},
                 {'randomSample': {'size': 1}}],
     'name': 'Placeholder so there is at least one pod scenario defined.'}
Policy not valid. See log output above.
```

**Environment (please complete the following information):**
Mac + Python 3.8.1
```
$ python --version
Python 3.8.1
$ uname -a
Darwin C02X4CCZJG5J.ad.here.com 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

**Comment by seeker89** [comment]
Awesome, thanks so much for catching this! I marked as good first issue.

**Comment by jcstanaway** [comment]
Thanks.  Going through our internal open source contribution process to submit a PR (missed doing that with #205).

**Comment by seeker89** [comment]
That's great to hear 👍
