### ISSUE TITLE
Powerfulseal pod doesn start in kubernetes cluster

### ISSUE THREAD

**Issue by rajivchirania** [bloomberg/powerfulseal#280]
**Describe the bug**
Powerfulseal pod doesn start in kubernetes cluster

I am trying to use the below policy to deploy a powerful seal pod in EKS cluster.

policy.yaml
------------
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealpolicy
  namespace: powerfulseal
data:
  policy.yml: |-
    scenarios:
    - name: "delete a random pod in kube-system namespace"
      steps:
      - matches:
        - labels:
            namespace: "kube-system"
            selector: "k8s-app=kube-dns"
        filters:
        - randomSample:
            size: 1
        actions:
        - kill:
            probability: 0.77
            force: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulseal
  namespace: powerfulseal
spec:
  replicas: 1
  selector:
    matchLabels:
        name: powerfulseal
  template:
    metadata:
      labels:
        name: powerfulseal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      serviceAccountName: powerfulseal
      containers:
        - name: powerfulseal
          image: store/bloomberg/powerfulseal:2.9.0
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --aws
          - --inventory-kubernetes
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yaml
              subPath: policy.yaml
      volumes:
        - name: policyfile
          configMap:
            name: sealpolicy

however the configmap does get created but pod fails to start with below error

2020-06-29 10:04:17 powerfulseal-68fb6cc456-vq29g powerfulseal[1] INFO modules powerfulseal.cli.__main__ : verbosity None : log level DEBUG : handler level ERROR
2020-06-29 10:04:17 powerfulseal-68fb6cc456-vq29g powerfulseal.cli.__main__[1] INFO Creating kubernetes client with in-cluster config
2020-06-29 10:04:17 powerfulseal-68fb6cc456-vq29g powerfulseal.k8s.k8s_client[1] INFO Initializing with config: None
2020-06-29 10:04:17 powerfulseal-68fb6cc456-vq29g powerfulseal[1] INFO Building AWS driver
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 684, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/cli/__main__.py", line 499, in main
    driver = AWSDriver()
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/clouddrivers/aws_driver.py", line 49, in __init__
    self.conn = create_connection_from_config()
  File "/usr/local/lib/python3.7/site-packages/powerfulseal/clouddrivers/aws_driver.py", line 9, in create_connection_from_config
    conn = boto3.resource('ec2')
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 85, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 287, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 301, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 361, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

I am assuming to the correct AWS environment and i can list all the kubernetes nodes and all.
Can someone help how to get the pod up and running

**Comment by seeker89** [comment]
It appears to be complaining about the region not being specified:

```py
raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

If you want to take AWS machines up and down, you will need to [specify the credentials the same way as you would for the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).

That said:

- your policy doesn't seem to be having any node actions - so you don't need the `--aws` flag
- you are using the 3.0 version style scenarios, but are using the `2.9.0` image - please update to a newer version, ideally by building from master branch

**Comment by rajivchirania** [comment]
@seeker89 but how do you pass the credentials to a powerseal pod config which is running in EKS cluster..
