### ISSUE TITLE
Seal crashes on listing pods in a namespace

### ISSUE THREAD

**Issue by skamboj** [bloomberg/powerfulseal#33]
I have some pods in a namespace `stresstest`:

```sh
$ kubectl get pods -n stresstest
NAME                       READY     STATUS    RESTARTS   AGE
mirrorer-bff584d74-ttcnz   1/1       Running   0          2d
mirrorer-bff584d74-vbs7l   1/1       Running   4          2d
v3-2-5-bdc8d9858-gptff     2/2       Running   0          2h
```

However attempting to retrieve the set of pods in my namespace seems to cause the seal to die and untimely death:

```sh
$ powerfulseal --inventory-kubernetes --interactive --kube-config /kubernetes/conf/kubeconfig
(seal) $ help pods

        List pods
        Syntax:
            pods namespace [selector]
        Selector is in the kubernetes native form: app=something,ver=1
        
(seal) $ pods stresstest 
Traceback (most recent call last):
  File "/home/cloud-user/powerfulseal/env/bin/powerfulseal", line 9, in <module>
    load_entry_point('powerfulseal==1.0.1', 'console_scripts', 'powerfulseal')()
  File "/home/cloud-user/powerfulseal/powerfulseal/cli/__main__.py", line 195, in start
    main(sys.argv[1:])
  File "/home/cloud-user/powerfulseal/powerfulseal/cli/__main__.py", line 178, in main
    cmd.cmdloop()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/cloud-user/powerfulseal/powerfulseal/cli/pscmd.py", line 346, in do_pods
    selector=selector
  File "/home/cloud-user/powerfulseal/powerfulseal/k8s/k8s_inventory.py", line 92, in find_pods
    ) for i, item in enumerate(pods)
  File "/home/cloud-user/powerfulseal/powerfulseal/k8s/k8s_inventory.py", line 92, in <listcomp>
    ) for i, item in enumerate(pods)
TypeError: 'NoneType' object is not iterable
```

I find that pods works fine in the default namespace but crashes even for the `kube-system` namespace.

**Comment by skamboj** [comment]
So it appears that this might be caused by evicted pods that still exist even though they don't show up when you do get pods:

```
$ kubectl describe pods v3-2-5-bdc8d9858-pk44d -n stresstest                                  
Name:           v3-2-5-bdc8d9858-pk44d
Namespace:      stresstest
Node:           <removed>
Start Time:     Thu, 28 Dec 2017 15:58:31 -0500
Labels:         name=stresstest
                pod-template-hash=687485414
                usvc=true
                version=3.2.5
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: nodefs.
IP:             
Controlled By:  ReplicaSet/v3-2-5-bdc8d9858
```
