### ISSUE TITLE
Kill command returned 'Node not found'

### ISSUE THREAD

**Issue by Jaesang** [bloomberg/powerfulseal#42]
Hello, I installed powerfulseal by pip in Ubuntu VM that was installed k8s.I ran into interactive mode, but It returns nothing when I executed kill pod, Is there any wrong or missed step?
```
root@taco-aio:~# powerfulseal --interactive --inventory-kubernetes --kube-config .kube/config
(seal) $ groups
amd64
enabled
linux
taco-aio
true
(seal) $ namespaces
ceph
default
kube-public
kube-system
openstack
(seal) $ pods openstack application=nova
[pod #0 name=nova-api-metadata-58d96477bc-5m8pf namespace=openstack containers=1 ip=172.16.106.22 host_ip=192.168.122.190 state
=Running labels:application=nova,pod-template-hash=1485203367,component=metadata,release_group=taco-nova]
[pod #1 name=nova-api-osapi-658fdf8688-knx9r namespace=openstack containers=1 ip=172.16.106.24 host_ip=192.168.122.190 state=Ru
nning labels:application=nova,pod-template-hash=2149894244,component=os-api,release_group=taco-nova]
[pod #2 name=nova-bootstrap-p6gw8 namespace=openstack containers=1 ip=172.16.106.49 host_ip=192.168.122.190 state=Succeeded lab
els:application=nova,controller-uid=cb019bea-0bbf-11e8-bca1-525400d69f89,component=bootstrap,job-name=nova-bootstrap,release_gr
oup=taco-nova]
[pod #3 name=nova-cell-setup-nmjk8 namespace=openstack containers=1 ip=172.16.106.28 host_ip=192.168.122.190 state=Succeeded la
bels:application=nova,controller-uid=cb039bf3-0bbf-11e8-bca1-525400d69f89,component=cell-setup,job-name=nova-cell-setup,release
_group=taco-nova]
[pod #4 name=nova-compute-5b9sx namespace=openstack containers=2 ip=192.168.122.190 host_ip=192.168.122.190 state=Running label
s:application=nova,pod-template-generation=1,component=compute,controller-revision-hash=3918579215,release_group=taco-nova]
[pod #5 name=nova-conductor-6cd6689fb9-6554f namespace=openstack containers=1 ip=172.16.106.44 host_ip=192.168.122.190 state=Ru
nning labels:application=nova,pod-template-hash=2782245965,component=conductor,release_group=taco-nova]
[pod #6 name=nova-consoleauth-f44969c95-tc9mx namespace=openstack containers=1 ip=172.16.106.35 host_ip=192.168.122.190 state=R
unning labels:application=nova,pod-template-hash=900525751,component=consoleauth,release_group=taco-nova]
[pod #7 name=nova-db-init-vbwrw namespace=openstack containers=3 ip=172.16.106.3 host_ip=192.168.122.190 state=Succeeded labels
:application=nova,controller-uid=cb07cca8-0bbf-11e8-bca1-525400d69f89,component=db-init,job-name=nova-db-init,release_group=tac
o-nova]
[pod #8 name=nova-db-sync-llvqc namespace=openstack containers=1 ip=172.16.106.41 host_ip=192.168.122.190 state=Succeeded label
s:application=nova,controller-uid=cb0c9fe1-0bbf-11e8-bca1-525400d69f89,component=db-sync,job-name=nova-db-sync,release_group=ta
co-nova]
[pod #9 name=nova-ks-endpoints-29zkm namespace=openstack containers=3 ip=172.16.106.7 host_ip=192.168.122.190 state=Succeeded l
abels:application=nova,controller-uid=cb11dcb7-0bbf-11e8-bca1-525400d69f89,component=ks-endpoints,job-name=nova-ks-endpoints,re
lease_group=taco-nova]
[pod #10 name=nova-ks-service-n2kcn namespace=openstack containers=1 ip=172.16.106.2 host_ip=192.168.122.190 state=Succeeded la
bels:application=nova,controller-uid=cb3709d5-0bbf-11e8-bca1-525400d69f89,component=ks-service,job-name=nova-ks-service,release
_group=taco-nova]
[pod #11 name=nova-ks-user-9lj5m namespace=openstack containers=1 ip=172.16.106.51 host_ip=192.168.122.190 state=Succeeded labe
ls:application=nova,controller-uid=cb3b1e7c-0bbf-11e8-bca1-525400d69f89,component=ks-user,job-name=nova-ks-user,release_group=t
aco-nova]
[pod #12 name=nova-novncproxy-7db5fb96b9-xtwph namespace=openstack containers=1 ip=192.168.122.190 host_ip=192.168.122.190 stat
e=Running labels:application=nova,pod-template-hash=3861965265,component=novnc-proxy,release_group=taco-nova]
[pod #13 name=nova-placement-api-5b794b96f8-dfhr2 namespace=openstack containers=1 ip=172.16.106.10 host_ip=192.168.122.190 sta
te=Running labels:application=nova,pod-template-hash=1635065294,component=placement,release_group=taco-nova]
[pod #14 name=nova-scheduler-59b5999769-jnr2n namespace=openstack containers=1 ip=172.16.106.9 host_ip=192.168.122.190 state=Ru
nning labels:application=nova,pod-template-hash=1561555325,component=scheduler,release_group=taco-nova]
(seal) $ kill 14
Node not found
(seal) $
```

**Comment by seeker89** [comment]
Hey, could you check out master branch and confirm that it works for you ?
If it doesn't please reopen this issue. If it does, let me know, and I'll release the updated version.

Thanks !

**Comment by Jaesang** [comment]
Hi @seeker89 
Thx for reply, but your commit doesn't execute 
```
root@taco-aio:/usr/local/lib/python3.5/dist-packages/powerfulseal/cli#
root@taco-aio:/usr/local/lib/python3.5/dist-packages/powerfulseal/cli# powerfulseal
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 11, in <module>
    load_entry_point('powerfulseal==1.2.0', 'console_scripts', 'powerfulseal')()
  File "/usr/local/lib/python3.5/dist-packages/powerfulseal/cli/__main__.py", line 229, in start
    main(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/powerfulseal/cli/__main__.py", line 113, in main
    help="aws cloud provider",
  File "/usr/local/lib/python3.5/dist-packages/configargparse.py", line 878, in add_argument
    action = self.original_add_argument_method(*args, **kwargs)
  File "/usr/lib/python3.5/argparse.py", line 1353, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1577, in _add_action
    action = self._container._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1716, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1557, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1367, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.5/argparse.py", line 1506, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.5/argparse.py", line 1515, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --aws-cloud: conflicting option string: --aws-cloud
```

your commit duplicated about --aws-cloud code in __main__.py

**Comment by seeker89** [comment]
@Jaesang you're right - thanks for catching that, not sure how it slipped through ! 

https://github.com/bloomberg/powerfulseal/pull/46 fixes it.

**Comment by rkharat** [comment]
I am getting same Node not found error while killing the node. I dont see solution for this.
Can you tell me how does it solved?
