### ISSUE TITLE
unable to run powerfulseal

### ISSUE THREAD

**Issue by maheshkolli** [bloomberg/powerfulseal#48]
I am trying to setup powerfulseal for  testing of our kubernetes cluster. Seeing following error message when I run version command.  I did install powerfulseal with pip install 

powerfulseal  --version
Traceback (most recent call last):
  File "/usr/bin/powerfulseal", line 11, in <module>
    load_entry_point('powerfulseal==1.1.1', 'console_scripts', 'powerfulseal')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/powerfulseal/cli/__main__.py", line 26, in <module>
    from ..clouddrivers import OpenStackDriver
  File "/usr/lib/python2.7/site-packages/powerfulseal/clouddrivers/__init__.py", line 17, in <module>
    from .driver import AbstractDriver
  File "/usr/lib/python2.7/site-packages/powerfulseal/clouddrivers/driver.py", line 20
    class AbstractDriver(metaclass=abc.ABCMeta):

**Comment by seeker89** [comment]
Hi @maheshkolli,

Like I just mentioned in #50, we currently only support python 3.4+.

Do you have a use case that requires you to use py27 ?

**Comment by maheshkolli** [comment]
Hi @seeker89 ,
My issue is resolved after following steps mentioned in #50 .I don't have an use case to use python2.7.  I will try to use python 3.4+ in the next environment and see how it goes. But it would be nice if you could support python 2.7 also.
Regards,
Mahesh

**Comment by seeker89** [comment]
Will close now. For now we don't have a lot of requests for support for python 2.7. Feel free to comment on #51 if that changes for you. Thanks
