### ISSUE TITLE
Issue with running powerfulseal 

### ISSUE THREAD

**Issue by poplavska** [bloomberg/powerfulseal#54]
I'm trying to run a powerful seal in virtual env and it's throwing me an error:

(env1) [ypoplavs@localhost]$ python -m powerfulseal.cli --kube-config path/to/config --inventory-kubernetes --interactive -v
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/powerfulseal/cli/__main__.py", line 198, in <module>
    start()
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/powerfulseal/cli/__main__.py", line 195, in start
    main(sys.argv[1:])
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/powerfulseal/cli/__main__.py", line 135, in main
    cloud=args.open_stack_cloud,
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/powerfulseal/clouddrivers/open_stack_driver.py", line 71, in __init__
    self.conn = create_connection_from_config(cloud)
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/powerfulseal/clouddrivers/open_stack_driver.py", line 26, in create_connection_from_config
    cloud = occ.get_one_cloud(name)
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/openstack/config/loader.py", line 1042, in get_one
    auth_plugin = loader.load_from_options(**config['auth'])
  File "/home/ypoplavs/env1/lib/python3.4/site-packages/keystoneauth1/loading/base.py", line 162, in load_from_options
    raise exceptions.MissingRequiredOptions(missing_required)
keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url

It seems like an error is related to Openstack provider, however, I am using AWS. Should i specify that provider is AWS? However, I do not see it as an argument in --help.

Thank you in advance.

**Comment by seeker89** [comment]
Hi @poplavska thanks for the issue.

It looks like you are running version 1.1.1, that used to only have OpenStack support.

Could you please try with the `master` branch ? In a fresh virtualenv, you can run something like

```sh
git clone git@github.com:bloomberg/powerfulseal.git
cd powerfulseal
pip install .
powerfulseal --help
```

We haven't published that to `pypi` because we were waiting on some more tests... But I guess at this stage we probably should.

Thanks !

**Comment by poplavska** [comment]
Thank you for help! It worked :)

However, one more question: is it possible to run powerfulseal through bastion or we have to gave a direct access to nodes? 
We're using 3 bastion hosts since we have 3 availability zones and if I leave only one, it shows nothing.
