### ISSUE TITLE
powerfullseal wont run

### ISSUE THREAD

**Issue by AlexShemeshWix** [bloomberg/powerfulseal#57]
Hi 
Ive installed powerfullseal but when i run it it gives me error

```
powerfulseal --help
Traceback (most recent call last):
  File "/usr/local/bin/powerfulseal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.3.7 (/usr/local/lib/python2.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), set(['pyasn1-modules']))
```
My python is 2.7.13
Ive tried it on virtualenv , tried to install master branch.
Nothing works.

**Comment by seeker89** [comment]
He @AlexShemeshWix please see https://github.com/bloomberg/powerfulseal/issues/51 - currently only python 3.6+ is supported. Could you please use a more modern python ?

**Comment by AlexShemeshWix** [comment]
Sure. What the hell
