### ISSUE TITLE
Fail to install powerfulseal because of locale?

### ISSUE THREAD

**Issue by calvinyv** [bloomberg/powerfulseal#71]
ubuntu 16.04
python 2.7.12

```
root@i-mki26uqf:/opt# python --version  
Python 2.7.12  
```
```
root@i-mki26uqf:/opt# pip install powerfulseal  
Traceback (most recent call last):  
  File "/usr/bin/pip", line 11, in <module>  
    sys.exit(main())  
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main  
    locale.setlocale(locale.LC_ALL, '')  
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale  
    return _setlocale(category, locale)  
locale.Error: unsupported locale setting  
```

**Comment by seeker89** [comment]
This looks like a problem with your setup. Check out [this response on stackoverflow](https://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting) - looks like it might be useful to you ?

**Comment by seeker89** [comment]
Hi @calvinyv any updates on this ?
Can we close the issue ?
