### ISSUE TITLE
App crashes in prometheus collector on Node stop action: 'Node' object has no attribute 'uid'

### ISSUE THREAD

**Issue by olga-mir** [bloomberg/powerfulseal#93]
Every time when the app tries to stop a node it will crash in prometheus collector, because object `Node` has no attribute `uid`.

It seems that `pod` object has this attribute, but not `node`:
https://github.com/bloomberg/powerfulseal/blob/f3014fa75477b1f123e87fa12df8e76491e3cd2a/powerfulseal/clouddrivers/aws_driver.py#L30-L39:
```
def create_node_from_server(server, ip):
    """ Translate AWS EC2 Instance representation into a Node object.
    """
    return Node(
        id=server.id,
        ip=ip,
        az=server.placement['AvailabilityZone'],
        name="",
        state=server_status_to_state(server.state),
)
```

Error: (removed actual values, note that `name` doesn't have a value, and also there is no field `uid`)
```
Filtered set length: 1
Acting on these: [[node no=xxx id=<ID> ip=xx.xx.xx.xx az=ZONE groups=['ARCH', 'AZ', 'INSTSANCE_TYPE', 'NODE_LABEL', 'ip-xx-xx-xx-xx', 'OS', 'node'] name= state=NodeState.UP]]
Action stop on [node no=xxx id=<ID> ip=xx.xx.xx.xx az=ZONE groups=['ARCH', 'AZ', 'INSTSANCE_TYPE', 'NODE_LABEL', 'ip-xx-xx-xx-xx', 'OS', 'node'] name= state=NodeState.UP]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/node_scenario.py", line 61, in action_stop
    self.metric_collector.add_node_stopped_metric(item)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/metriccollectors/prometheus_collector.py", line 73, in add_node_stopped_metric
    NODE_STOPS.labels(STATUS_SUCCESS, node.uid, node.name).inc()
AttributeError: 'Node' object has no attribute 'uid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/bin/powerfulseal", line 11, in <module>
    load_entry_point('powerfulseal', 'console_scripts', 'powerfulseal')()
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/cli/__main__.py", line 391, in start
    main(sys.argv[1:])
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/cli/__main__.py", line 387, in main
    metric_collector=metric_collector)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/policy_runner.py", line 88, in run
    scenario.execute()
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/scenario.py", line 65, in execute
    self.act(filtered_set)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/node_scenario.py", line 90, in act
    return self.act_mapping(items, actions, mapping)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/scenario.py", line 221, in act_mapping
    method(item, params)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/policy/node_scenario.py", line 64, in action_stop
    self.metric_collector.add_node_stop_failed_metric(item)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/src/powerfulseal/powerfulseal/metriccollectors/prometheus_collector.py", line 76, in add_node_stop_failed_metric
    NODE_STOPS.labels(STATUS_FAILURE, node.uid, node.name).inc()
```

Pipefile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
powerfulseal = {git = "git://github.com/bloomberg/powerfulseal.git", editable = true, ref = "master"}
Pipfile = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

Start command:
```
pipenv run powerfulseal --inventory-kubernetes --aws-cloud --kube-config ~/.kube/config  --prometheus-collector --prometheus-host '0.0.0.0' --prometheus-port 8080  --remote-user core --ssh-allow-missing-host-keys --verbose -v --run-policy-file chaos_policy.yml
```

If prometheus is not enabled the app works fine

**Comment by seeker89** [comment]
I've knocked this out through the UI (away from keyboard), but the CI seems to be happy: https://github.com/bloomberg/powerfulseal/pull/95 - check it out when you have a moment 😄

**Comment by olga-mir** [comment]
thank you for addressing this promptly
